name = "HM Basic Play"
author = "henrymmey"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f659a5fdd71709e5bc35d84fa56c9cb69661bf211143eee14c0801160adc6d64"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
