name = "HM Basic Play"
author = "henrymmey"
version = "26.3-1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d7de175e08c7abc223a6fec428dd9379bdf51e473435a792cb128f76686fa62a"

[versions]
fabric = "0.19.5"
minecraft = "26.3"
