name = "HM Basic Play"
author = "henrymmey"
version = "26.3-1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "25b643868e9b0c28cac70c94e69cee1936fac955774f80afdb709aa9635d7541"

[versions]
fabric = "0.19.5"
minecraft = "26.3"
